version: '3'
services:
    web: 
        container_name: nginx
        ports: 
            - "8080:80"
        image: nginx
        volumes:
            "vol2:/usr/share/nginx/html"
volumes:
    vol2: