version: '3'
services:
    dbmysql:
        mem_limit: 256m
        image: mysql:5.6.51
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        networks: 
            - net-docker
        volumes: 
            - "./mysql/data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 123456Zxcv  
        ports:
            - "3360:3306"          
    web: 
        container_name: nginx
        mem_limit: 256m
        depends_on: 
            - nodejs
        ports: 
            - "8025:80"
            - "8026:8080"
        image: nginx
        volumes:
            - ./html/compras-menores:/usr/share/nginx/html/compras-menores
            - ./html/portal-ciudadano:/usr/share/nginx/html/portal-ciudadano
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks: 
            - net-docker
        restart: always    
    nodejs:
        mem_limit: 256m
        depends_on: 
            - db
        build:
            context: ./rest-api/node_postgres
            dockerfile: Dockerfile
        container_name: nodejs
        # volumes: 
        #     - "//c/Docker/compras-menores/node_postgres:/app"
        ports:
            - "3002:3002"
        networks: 
            - net-docker
    nodejscovid:
        mem_limit: 256m
        restart: always
        depends_on: 
            - dbmysql
        build:
            context: ./node_covid
            dockerfile: Dockerfile
        container_name: nodejscovid
        # volumes: 
        #     - "//c/Docker/compras-menores/node_postgres:/app"
        ports:
            - "3050:5000"
        networks: 
            - net-docker
    esn2021:
        mem_limit: 256m
        depends_on: 
            - db
        build:
            context: ./html/esn2021
            dockerfile: Dockerfile
        container_name: esn2021
        volumes: 
            - "./html/esn2021/core:/app"
        ports:
            - "5021:5000"
            
        networks: 
            - net-docker
    inocuidad:
        mem_limit: 256m
        depends_on: 
            - db
        build:
            context: ./html/inocuidad
            dockerfile: Dockerfile
        container_name: inocuidad
        volumes: 
            - "./html/inocuidad/core:/app"
        ports:
            - "5022:5000"
        networks: 
            - net-docker
    transporte:
        mem_limit: 256m
        depends_on: 
            - db
        build:
            context: ./html/transporte
            dockerfile: Dockerfile
        container_name: transporte
        volumes: 
            - "./html/transporte/core:/app"
        ports:
            - "5023:5000"
        networks: 
            - net-docker
    ayudasantacruz:
        mem_limit: 256m
        # depends_on: 
        #     - db
        build:
            context: ./html/ayudasantacruz
            dockerfile: Dockerfile
        container_name: ayudasantacruz
        volumes: 
            - "./html/ayudasantacruz/core:/app"
        ports:
            - "5024:5000"
        networks: 
            - net-docker
    comprascheques:
        mem_limit: 256m
        depends_on:
            - db
        build:
            context: ./html/comprascheques
            dockerfile: Dockerfile
        container_name: comprascheques
        volumes: 
            - "./html/comprascheques/core:/app"
        ports:
            - "5025:5000"
        networks: 
            - net-docker
    basangularcore:
        mem_limit: 256m
        depends_on:
            - db
        build:
            context: ./html/bas-angular-core
            dockerfile: Dockerfile
        container_name: basangularcore
        volumes: 
            - "./html/bas-angular-core/core:/app"
        ports:
            - "5026:5000"
        networks: 
            - net-docker
    baslaravel:
        mem_limit: 256m
        depends_on:
            - db
        build:
            context: ./html/bas-laravel
            dockerfile: Dockerfile
        container_name: baslaravel
        ports:
            - "8027:8000"
            - "8028:80"
        networks: 
            - net-docker

    covid19buscador:
        mem_limit: 256m
        depends_on: 
            - dbmysql
            - nodejscovid
        build:
            context: ./html/covid19-Buscador
            dockerfile: Dockerfile
        container_name: covid19buscador
        # volumes: 
        #     - "./html/covid19-Buscador:/usr/src/nuxt-app"
        ports:
            - "3004:5000"
        networks: 
            - net-docker

    db:
        container_name: postgres
        image: postgres
        restart: always
        volumes:
            - "./db_postgres:/var/lib/postgresql/data"
        environment:
            POSTGRES_PASSWORD: 12345678
        ports:
            - "5434:5432"
        networks: 
            - net-docker
    mariadb:
        mem_limit: 256m
        image: docker.io/bitnami/mariadb
        environment:
            - MARIADB_USER=bn_jasperreports
            - MARIADB_DATABASE=bitnami_jasperreports
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - './mariadb_report:/bitnami'
        networks: 
            - net-docker
    jasperreports:
        mem_limit: 512m
        image: docker.io/bitnami/jasperreports
        environment:
            - MARIADB_HOST=mariadb
            - MARIADB_PORT_NUMBER=3306
            - JASPERREPORTS_DATABASE_USER=bn_jasperreports
            - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '8029:8080'
        networks: 
            - net-docker
        volumes:
            - './jasperreports:/bitnami'
        depends_on:
            - mariadb
    adminer:
        mem_limit: 256m
        image: adminer
        restart: always
        ports:
            - 8034:8080
        networks: 
            - net-docker
networks: 
    net-docker:
