version: '3.7'
services: 
    mysql_db_container:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports: 
          - 3306:3306
        volumes: 
            - ./data:/var/lib/mysql

volumes: 
    data: 