# Use root/example as user/password credentials
version: '3.1'

services:

  dbmysql:
    image: mysql:5.6.51
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
        - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456Zxcv

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080